### ISSUE TITLE
Supporting import maps

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#6]
# Issue
Support import maps

## Details
I see there is a comment about "import source maps" at the end of https://github.com/cmorten/deno-rollup/blob/main/src/rollup-plugin-deno-resolver/denoResolver.ts. I assume this means "import maps", though I would have thought this was for the `resolveId` hook rather than `load`.

I've managed to get support working in Denopack, which is similar to this repo, but have got frustrated by the lack of activity there.

In Denopack, I'm using https://github.com/timreichen/importmap which requires some fiddling around with the url to get it to work with all the map types I want to use.

These are:
* 1to1 remap, which covers Node-style 'bare' specifiers as well as simple 1to1 url mapping
* trailing slash remap, such as `theirlib/`, meaning the code imports from `theirlib/...`, and the import map determines where `theirlib` should be loaded from
* baseUrl remap, such as `/lib/file.js`. In Deno, baseUrl will be `cwd`, so import specifiers have to be resolved to cwd before comparing to the import map entry (this is where the fiddling around is needed with timreichen's plugin).

 I think it's simplest to pass the import map with the options, then the user can decide whether that is read from an external file or defined in the config file.

As `Deno.emit()` includes import mapping (I've not tested this), another possibility would be to run all files through `emit()` and let that handle the remapping. However, as `emit()` seems to be very slow, maybe that's not such a good idea :-)

**Comment by cmorten** [comment]
Ah so that particular TODO is regarding sourcemaps for code imported from a remote URL, e.g. 

```ts
import { basename } from "https://deno.land/std@0.83.0/path/mod.ts";

console.log(basename(Deno.cwd()));
```

Rollup core was never designed to work with URLs, so the sourcemaps generated out-of-the-box have the sources like `../https:/deno.land/std@0.83.0/path/mod.ts` (or sim) which is not valid. That TODO is to handle this better with valid URLs for the sources.

**Comment by probins** [comment]
a really simple plugin, basically just a wrapper around timreichen's module seems to work fine for the first 2 cases:
```js
import { resolve } from "https://deno.land/x/importmap/mod.ts";
export function importMapPlugin(options) {
  return {
    name: "importMapPlugin",
    resolveId: (source, importer) => {
      return resolve(source, options.importMap, importer);
    }
  };
};
```
then pass the import map in the options:
```js
  plugins: [
    importMapPlugin({
      "importMap": {
        "imports": {
          "theirlib/": "https://cdn.jsdelivr.net/gh/user/project@1.2.3/src/",
          "npmpkg": "https://jspm.dev/npmpkg"
        }
      }
    }),
```
The 3rd case needs a bit more work, but I'll discuss this with timreichen; IMO, this belongs in his module, not the plugin.

So, deno-rollup can support import maps without having to do anything. 😄

**Comment by cmorten** [comment]
Looks great - if I understand correctly there isn’t anything required of this repo then? (If not then can close this issue)

**Comment by probins** [comment]
ok, will close

**Comment by probins** [comment]
I'll reopen this, as what I thought was a solution only works if the map-to address is a fully resolved url (which happened to be the case in the examples I was using).

If the matched address is a local file, then it needs to be resolved in the usual way using `resolveId()` at https://github.com/cmorten/deno-rollup/blob/main/src/rollup-plugin-deno-resolver/denoResolver.ts#L40. Perhaps this could be put in a separate module that an importMap plugin could import? Alternatively, the code to support import maps could be incorporated in `resolveId()` - it is part of the resolution process - perhaps as a separate module that `resolveId()` uses.

**Comment by cmorten** [comment]
Do you have a link to this "importMap plugin" - it feels like handling the various resolution cases should be it's responsibility. Once a plugin is used that returns a non-null `id` from a `resolveId`, afaik it will not be re-resolved via another plugin - effective what the core of this library is.

Recommend taking a look at https://github.com/rollup/rollup/issues/1356, there are a few use-cases suggested for being able to chain `resolveId` methods, one including an import map use-case. It isn't available in Rollup itself however so there is little I can do in this library to overcome that limitation without re-implementing the plugin architecture.

As per <https://github.com/rollup/rollup/issues/1356#issuecomment-470808155>, the recommendation is to call `this.resolveId` from your plugin context (where need to take care to avoid infinite loops etc.).

REF: https://rollupjs.org/guide/en#this-resolveid-importee-string-importer-string-string

The alternative to all of the above to solve your issue would be to support import maps natively to this library. That is the Deno resolver in this repo handles import maps itself without the need of any additional plugins. There have been some questions in my mind whether import maps are going supported in the future (sure I read on Reddit a while back that they might be dropped, might also be mis-remembering!). The feature is also unstable... but then again so are some of the core features of this library, so that isn't much of an excuse.

If you're able to share an example of an existing library for supporting import maps, then I don't imagine it would be much work to support them here. Especially given we may just be able to pass it all to `Deno.emit()` and it take care of it - investigation needed!

**Comment by probins** [comment]
I'm far from expert in Rollup plugins, but AIUI if you return null then it will be passed to the Rollup default. But this is not what is needed here: it returns the remapped address, which then has to be resolved (if the remapped address is not a fully resolved url). Effectively the mapping has to be done before the resolving plugin. I think `this.resolveId()` has been replaced by `this.resolve()`, but I'm not sure that will work in this case; I don't want to call Rollup's default, but to call this repo's plugin function for use in Deno context. 

Chromium has had an import maps implementation behind a flag for some time, but they shipped this last month https://bugs.chromium.org/p/chromium/issues/detail?id=848607#c40, so it should be enabled by default in Chrome 89, due to pass to beta today IIRC. I've been using it with the flag for a while now.

The code I've been trying to use isn't complicated - essentially the function at https://github.com/timreichen/importmap/blob/master/mod.ts#L36 wrapped as a Rollup plugin. This checks for exact match, and for matches with trailing slash, but doesn't match baseUrl specifiers. In addition, the module simply returns the matched specifier, which then needs to be resolved.

**Comment by probins** [comment]
so, here's my revised plugin which works for all 3 cases listed in my original post, using timreichen's module for the mapping:
```js
import { resolve } from "https://deno.land/x/importmap@0.1.4/mod.ts";
import { fromFileUrl, join, toFileUrl } from "https://deno.land/std@0.84.0/path/mod.ts";

export function importMapPlugin(options) {
  return {
    name: "importMapPlugin",
    resolveId: (source, importer) => {
      let baseURL = importer;
      const cwd = Deno.cwd();
      // if importer is a file:// URL, convert to baseURL, i.e. remove protocol and cwd
      if (importer && importer.startsWith('file://')) {
        baseURL = fromFileUrl(importer).replace(cwd,'')
      }
      // resolve() only uses baseURL if source not a URL
      let matchedAddress = resolve(source, options.importMap, baseURL);
      // if returned address not a resolved URL, convert to file URL
      const URL = /^(https?|file):\/\//;
      if (!URL.test(matchedAddress)) {
        matchedAddress = toFileUrl(join(cwd, '/', matchedAddress)).toString();
      }
      return matchedAddress;
    }
  };
};
```
Basically, this repo's `resolveId()` converts relative and absolute paths to file:// urls, so importer will always be a resolved url.
The import map module OTOH expects it to be in the form of a baseUrl. I've suggested that this be changed so it can also handle a resolved file:// url. If that is done, then the conversion code here can be removed. If a way can be found for the plugin to call `resolveId()`, then the converstion to file url can also be removed.

**Comment by cmorten** [comment]
I have released <https://github.com/cmorten/deno-rollup/tree/main/plugins/importmap> to try and support this as a plugin in this repo. Please let me know if it meets your use-cases.

**Comment by probins** [comment]
I'll test this out, thanks

**Comment by probins** [comment]
Looks like it supports the 1st and 2nd, but not the 3rd - the case described in https://github.com/WICG/import-maps#general-url-like-specifier-remapping.

https://github.com/cmorten/deno-rollup/blob/main/plugins/importmap/mod.ts#L178 matches exact equal (case 1) and trailing slash for directory match (case 2), but it's not checking for resolved path match (case 3). In this case, the import map entry is for example `/lib/file.js`, the source might be `./file.js` with importer `lib/otherfile.js`. The function correctly resolves importer to `/lib/otherfile.js`, but then doesn't resolve the source to base to compare with the import map entry.

These 3 are the ones I'm interested in atm. I've not been through all these tests, but Chromium's test suite is at https://chromium.googlesource.com/chromium/src/+/1d1222b38aeaef805af41683c3648623b710b7b2/third_party/blink/web_tests/external/wpt/import-maps/data-driven/resources and it looks like the 'official' spec tests are at https://github.com/web-platform-tests/wpt/tree/master/import-maps/data-driven/resources. Quite complicated, because of all the different variations.

**Comment by probins** [comment]
from the flurry of recent issues on the Deno repo, looks like they're planning to make import maps stable for 1.8, due March 2 - which happens to be the day Chrome 89 (where import maps are enabled by default) is due for release too.
